# Generated by Django 4.0.1 on 2022-01-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='descrição',
            field=models.TextField(blank=True, null=True),
        ),
    ]
