# Generated by Django 4.0.1 on 2022-01-13 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escola', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimeiroAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('origem', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Panfletos', 'Panfletos'), ('Faixas', 'Faixas'), ('Matriz', 'Matriz'), ('Outros', 'Outros')], max_length=50)),
                ('agendado', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=50)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observações', models.TextField(blank=True, null=True)),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('curso_desejado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escola.cursos')),
            ],
        ),
    ]
