# Generated by Django 4.0.1 on 2022-01-13 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primeiroatendimento',
            name='curso_desejado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.cursos'),
        ),
    ]
