# Generated by Django 4.0.1 on 2022-01-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
    ]
