# Generated by Django 4.0.1 on 2022-01-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='observações',
            field=models.TextField(blank=True, null=True),
        ),
    ]
