# Generated by Django 4.0.1 on 2022-01-15 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0003_primeiroatendimento_alter_agendamento_cliente_and_more'),
        ('clientes', '0003_alter_primeiroatendimento_curso_desejado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrimeiroAtendimento',
        ),
    ]
