# Generated by Django 4.0.1 on 2022-01-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
    ]
