# Generated by Django 4.0.1 on 2022-01-16 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escola', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(blank=True, max_length=50, null=True)),
                ('telefone', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('cpf', models.CharField(blank=True, max_length=50, null=True)),
                ('origem', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Panfletos', 'Panfletos'), ('Faixas', 'Faixas'), ('Matriz', 'Matriz'), ('Outros', 'Outros')], max_length=50)),
                ('agendado', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=50)),
                ('data', models.DateField()),
                ('horário', models.CharField(choices=[('08:00 as 09:00', '08:00 as 09:00'), ('09:00 as 10:00', '09:00 as 10:00'), ('11:00 as 12:00', '11:00 as 12:00'), ('12:00 as 13:00', '12:00 as 13:00'), ('13:00 as 14:00', '13:00 as 14:00'), ('14:00 as 15:00', '14:00 as 15:00'), ('15:00 as 16:00', '15:00 as 16:00'), ('16:00 as 17:00', '16:00 as 17:00'), ('17:00 as 16:00', '17:00 as 16:00'), ('17:00 as 18:00', '17:00 as 18:00'), ('18:00 as 19:00', '18:00 as 19:00'), ('ESPECIAL', 'ESPECIAL')], max_length=50)),
                ('descrição_do_atendimento', models.TextField(blank=True, null=True)),
                ('data_de_criação', models.DateTimeField(auto_now_add=True)),
                ('última_modificação', models.DateTimeField(auto_now=True)),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('curso_desejado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.cursos')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('comprou', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=50)),
                ('observações', models.TextField(blank=True, null=True)),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atendimento.contato')),
                ('curso_comprado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.cursos')),
                ('forma_de_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atendimento.formapagamento')),
            ],
        ),
    ]
