# Generated by Django 4.0.1 on 2022-01-12 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horário', models.CharField(choices=[('1º', '08:00 as 09:00'), ('2º', '09:00 as 10:00'), ('3º', '11:00 as 12:00'), ('4º', '12:00 as 13:00'), ('5º', '13:00 as 14:00'), ('6º', '14:00 as 15:00'), ('7º', '15:00 as 16:00'), ('8º', '16:00 as 17:00'), ('9º', '17:00 as 16:00'), ('10º', '17:00 as 18:00'), ('11º', '18:00 as 19:00'), ('12º', 'ESPECIAL')], max_length=50)),
                ('observações', models.TextField(blank=True, null=True)),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
            ],
        ),
    ]
