# Generated by Django 4.0.1 on 2022-01-13 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_primeiroatendimento_curso_desejado'),
        ('escola', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoPresencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('comprou', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=50)),
                ('observações', models.TextField(blank=True, null=True)),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.primeiroatendimento')),
                ('curso_desejado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.cursos')),
            ],
        ),
    ]
