# Generated by Django 4.0.1 on 2022-01-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_alter_contato_options_alter_contato_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='data',
        ),
        migrations.AddField(
            model_name='contato',
            name='data_do_agendamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
