# Generated by Django 4.0.1 on 2022-01-18 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0003_remove_contato_data_contato_data_do_agendamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='data_do_agendamento',
            new_name='data',
        ),
    ]
