# Generated by Django 4.0.1 on 2022-01-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0004_formapagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='cliente',
            field=models.CharField(max_length=50),
        ),
    ]
