# Generated by Django 4.0.1 on 2022-01-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0004_rename_data_do_agendamento_contato_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data',
            field=models.DateField(),
        ),
    ]
