# Generated by Django 4.0.1 on 2022-01-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0007_alter_contato_descrição_do_atendimento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'ordering': ('-data_de_criação',)},
        ),
        migrations.AlterField(
            model_name='contato',
            name='data_de_criação',
            field=models.DateField(auto_now_add=True),
        ),
    ]
