# Generated by Django 4.0.1 on 2022-01-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0008_alter_contato_options_alter_contato_data_de_criação'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data_de_criação',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
