# Generated by Django 4.0.1 on 2022-02-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0009_alter_contato_data_de_criação'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
